version: '2'
services:
  influxdb-handle:
    build:
      context: ./
      dockerfile: Dockerfile
    image: influxdb-ha/handle
    ports:
      - "8084:8084"
      - "8086:8086"
    entrypoint: bin/handle
    hostname: influxdb-handle
    depends_on:
      - etcd-1
      - influxdb-1
    command: -etcd "etcd-1:2379" -client-port 8086 -data "influxdb-1:8086"
  influxdb-handle2:
    image: influxdb-ha/handle
    ports:
      - "8184:8184"
      - "8186:8186"
    hostname: influxdb-handle2
    depends_on:
      - influxdb-handle
      - etcd-1
      - influxdb-2
    entrypoint: bin/handle
    command: -etcd "etcd-1:2379" -client-port 8186 -data "influxdb-2:8086"
  influxdb-handle3:
    image: influxdb-ha/handle
    ports:
      - "8284:8284"
      - "8286:8286"
    hostname: influxdb-handle3
    depends_on:
      - influxdb-handle2
      - etcd-1
      - influxdb-3
    entrypoint: bash
    command: -c 'sleep 1 && bin/handle -etcd "etcd-1:2379" -client-port 8286 -data "influxdb-3:8086"'

  influxdb-1:
    image: influxdb:1.2
    ports:
      - "28086:8086"
    hostname: influxdb-1
  influxdb-2:
    image: influxdb:1.2
    ports:
      - "27086:8086"
    hostname: influxdb-2
  influxdb-3:
    image: influxdb:1.2
    ports:
      - "26086:8086"
    hostname: influxdb-3


  etcd-1:
    image: quay.io/coreos/etcd:v3.1.4
    ports:
      - "2379:2379"
    hostname: etcd-1
    command: "etcd --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd-1:2379"
