apiVersion: v1
kind: Service
metadata:
  name: influxc
  labels:
    app: influxc
spec:
  ports:
  - port: 8087
    name: web
  type: NodePort
  selector:
    app: influxc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influx-cluster
spec:
  selector:
    matchLabels:
      app: influxc # has to match .spec.template.metadata.labels
  serviceName: "influxc"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: influxc # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: influxc
        image: docker.io/adamringhede/influxdb-cluster:latest
        command: ["bin/handle"]
        args: ["-etcd", "etcd:2379", "-client-port", "8087", "-data", "localhost:8086"]
        ports:
        - containerPort: 8087
          name: web
        lifecycle:
          preStop:
            exec:
              command:
              - echo "stop"
              # run a command to gracefully remove the node.
              # if the command has a drain mode, it should wait until other nodes have been able to recover the data
      - name: influxd
        image: influxdb:1.2
        ports:
        - containerPort: 8086
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 256Mi
